name: Build and Deploy Porra

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas jinja2 python-dotenv

      - name: Build site w/ jinja2
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: python main.py
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'